vyos:
  hosts:
    10.0.17.200:
      hostname: fw-blue1
      lan_ip: 10.0.5.2
      lan: 10.0.5.0/24
      dhcp_nameserver: 10.0.5.5
      network_name: BLUE1
      dhcp_domain: blue1.local
      mac: 00:50:56:a4:f4:d4

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: network_cli
    ansible_network_os: vyos
    ansible_user: vyos
