- name: vyos network config
  hosts: vyos
  tasks:
  - name: Get vyos version
    vyos_command:
      commands: show version
    register: version
  - debug:
      var: version.stdout_lines

  - name: Configure vyos DHCP
    vyos_config:
      save: yes
      lines:
      - set service dhcp-server global-parameters 'local-address {{ lan_ip }};'
      - set service dhcp-server shared-network-name {{ network_name }} authoritative
      - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} default-router '{{ lan_ip }}'
      - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} name-server '{{ dhcp_nameserver }}'
      - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} domain-name '{{ dhcp_domain }}'
      - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} lease '86400'
      - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} range {{ network_name }}-POOL start '10.0.5.75'
      - set service dhcp-server shared-network-name {{ network_name }} subnet {{ lan }} range {{ network_name }}-POOL stop '10.0.5.125'
